name: Travis
description: LOG your TRAVEL

publish_to:

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^5.0.0
  flutter_native_splash: ^2.3.1
  http: ^1.1.0
  google_maps_flutter: ^2.3.1
  location: ^5.0.0
  sliding_up_panel: ^2.0.0+1
  fluttertoast: ^8.2.2
  intl: ^0.18.1
  geolocator: ^9.0.2
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/
