name: myapp
description: A exported flutter project from FUNCTION12

publish_to:

version: 1.0.0+1

environment:
  sdk:
dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^5.0.0
  flutter_native_splash: ^2.3.1
  http: ^1.1.0
  google_maps_flutter: ^2.3.1
  location: ^5.0.0
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  permission_handler: ^9.2.0
  file_picker: ^4.5.1
  provider: ^6.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/
